events {}

http {

    upstream frontend {
        server frontend:3000;
    }

    upstream backend {
        server backend:8000;
    }

    server {

        listen 80;

        server_name siddardha.online www.siddardha.online;

        # FastAPI Swagger
        location /docs {
            proxy_pass http://backend;
        }

        location /openapi.json {
            proxy_pass http://backend;
        }

        location /redoc {
            proxy_pass http://backend;
        }

        # Backend APIs
        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://backend;
        }

        location /health {
            proxy_pass http://backend;
        }

        # Frontend
        location / {
            proxy_pass http://frontend;
        }
    }
}
